services:
  db:
    container_name: "sika-3"
    image: postgres:14
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      PGDATA: /data/postgres
      POSTGRES_DB: "sika-db"
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  db:
    driver: bridge

volumes:
  db: